name: Test

on:
  push:
    branches:
      - "master"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Download Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - name: Install Chrome
        run: sudo dpkg -i google-chrome-stable_current_amd64.deb
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -s -vv --alluredir=allure-results

#      - name: Run pytest
#        uses: pavelzw/pytest-action@v2
#        with:
#          verbose: true
#          emoji: true
#          job-summary: true
#          custom-arguments: '-q'
#          click-to-expand: true
#          report-title: 'Test Report'


      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
